FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["DemoGenerator.csproj", "DemoGenerator/"]
RUN dotnet restore "DemoGenerator/DemoGenerator.csproj"
COPY . "DemoGenerator/"
WORKDIR "/src/DemoGenerator"
RUN dotnet build "DemoGenerator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DemoGenerator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DemoGenerator.dll"]
