version: "3.9"
services:

  organization-service:
    image: showcase/organization-service
    restart: unless-stopped
    environment:
      NEO4J_URL: "bolt://graph-db:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "neo4j"
    ports:
      - 8082:8080
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "false"