version: "3.9"
services:

  reverse-proxy:
    build: .
    image: showcase/reverse-proxy
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443